# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Latin@s in Tech
email: organizers@techqueria.org
description: > # this means to ignore newlines until "baseurl:"
  Calling all latin@s in tech! Whether you just got here last week or your family is been in the country for decades, we have a lot to share and be proud of. Come share your experiences with the community
baseurl: "" # the subpath of your site, e.g. /blog
url: https://techqueria.org # the base hostname & protocol for your site
enforce_ssl: techqueria.org   # without any protocol

twitter_username: techqueriasf
github_username:  techqueria

# Build settings
markdown: kramdown
