baseURL                              = "https://techqueria.org/"
buildFuture                          = true
copyright                            = "This work is licensed under MIT."
enableEmoji                          = true
enableRobotsTXT                      = true
footnoteReturnLinkContents           = "↩"
metaDataFormat                       = "yaml"
title                                = "Techqueria"

# Language
languageCode                         = "en-US"
defaultContentLanguage               = "en"
enableMissingTranslationPlaceholders = true

# Categories
preserveTaxonomyNames                = false

# Code
pygmentsCodefences                   = true
pygmentsCodefencesGuessSyntax        = true
pygmentsStyle                        = "manni"

# Internal Templates
googleAnalytics                      = "UA-88917358-1"
disqusShortname                      = "techqueria"

# RSS
[outputs]
    home                             = ["HTML", "AMP", "RSS"]
    page                             = ["HTML", "AMP"]

[outputFormats]
    [outputFormats.RSS]
        mediatype                    = "application/rss"
        baseName                     = "feed"

# SEO
[params]
    description                      = "Techqueria is one of the largest communities for Latinx professionals in the tech industry. 🌮"
    year                             = 2015
    og_image                         = "https://i.imgur.com/O2YyA3E.png"
    logo                             = "https://i.imgur.com/iJpGY6L.png"
    locale                           = "en_US"
    default_content_language         = "en"

# Social Links
[social]
    email                            = "organizers@techqueria.org"
    facebook                         = "techqueria"
    instagram                        = "techqueriala"
    linkedin                         = "company/techqueria"
    meetup                           = "techqueria"
    twitter                          = "Techqueria"
    youtube                          = "UCUhXR0BOgyqrS1E_Sr4PVjQ"

# Permalinks
[permalinks]
  blog                               = "/blog/:year/:month/:day/:title/"
  testimonials                       = "/testimonials/:year/:month/:day/:title/"
  press                              = "/press/:year/:month/:day/:title/"

[author]
    name                             = "Techqueria"
    copyright                        = "©️ Techqueria.org"

# About
    # Blog
    # Brand
    # Code of Conduct
    # Contact
    # Events
    # Press
    # Team
    # Shop
# Communities
    # City Chapters
    # Eventbrite
    # Facebook Group
    # Facebook Page
    # GitHub Organization
    # Instagram
    # LinkedIn Group
    # LinkedIn Page
    # Meetup Group
    # Newsletter
    # Slack Workspace
    # Twitter
    # YouTube Channel
# Donate
    # Contribute on Open Collective
    # Contribute on Patreon
# Resources
    # Career Growth
    # Conferences
    # Design
    # Entrepeanurship
    # Health Care
    # Housing
    # Immigration
    # Legal Help
    # Nonprofits
    # Open Source
    # Podcasts
    # Similar Organizations
    # Students
# Sponsor Us
    # Our Current Sponsors
    # Become a volunteer
    # Donate space

# Twitter
# LinkedIn

# Join our Slack
# Login into Slack

[[menu.main]]
    name                             = "About"
    url                              = "/about/"
[[menu.main]]
    parent                           = "About"
    name                             = "Blog"
    url                              = "/blog/"
[[menu.main]]
    parent                           = "About"
    name                             = "Brand"
    url                              = "/brand/"
[[menu.main]]
    parent                           = "About"
    name                             = "Contact"
    url                              = "/contact/"
[[menu.main]]
    parent                           = "About"
    name                             = "Events"
    url                              = "/events/"
[[menu.main]]
    parent                           = "About"
    name                             = "Press️"
    url                              = "/press/"
[[menu.main]]
    parent                           = "About"
    name                             = "Team"
    url                              = "/team/"
[[menu.main]]
    parent                           = "About"
    name                             = "Shop"
    url                              = "/shop/"

[[menu.main]]
    name                             = "Communities"
    url                              = "/communities/"
[[menu.main]]
    parent                           = "Communities"
    name                             = "City Chapters"
    url                              = "/communities/chapters/"
[[menu.main]]
    parent                           = "Communities"
    name                             = "Eventbrite"
    url                              = "https://techqueria.eventbrite.com"
[[menu.main]]
    parent                           = "Communities"
    name                             = "Facebook Group"
    url                              = "https://www.facebook.com/groups/techqueria"
[[menu.main]]
    parent                           = "Communities"
    name                             = "Facebook Page"
    url                              = "https://www.facebook.com/techqueria"
[[menu.main]]
    parent                           = "Communities"
    name                             = "GitHub Organization"
    url                              = "https://github.com/techqueria"
[[menu.main]]
    parent                           = "Communities"
    name                             = "LinkedIn Group"
    url                              = "https://www.linkedin.com/groups/13500636"
[[menu.main]]
    parent                           = "Communities"
    name                             = "LinkedIn Page"
    url                              = "https://www.linkedin.com/company/techqueria/"
[[menu.main]]
    parent                           = "Communities"
    name                             = "Meetup Group"
    url                              = "https://www.meetup.com/techqueria/"
[[menu.main]]
    parent                           = "Communities"
    name                             = "Newsletter"
    url                              = "https://mailchi.mp/c12256627e10/techqueria-newsletter"
[[menu.main]]
    parent                           = "Communities"
    name                             = "Slack Workspace"
    url                              = "/communities/slack/"
[[menu.main]]
    parent                           = "Communities"
    name                             = "Twitter"
    url                              = "https://twitter.com/Techqueria"
[[menu.main]]
    parent                           = "Communities"
    name                             = "YouTube Channel"
    url                              = "https://www.youtube.com/channel/UCUhXR0BOgyqrS1E_Sr4PVjQ"

[[menu.main]]
    name                             = "Donate"
    url                              = "/donate/"
[[menu.main]]
    parent                           = "Donate"
    name                             = "Contribute on Open Collective"
    url                              = "https://opencollective.com/techqueria/"
[[menu.main]]
    parent                           = "Donate"
    name                             = "Contribute on Patreon"
    url                              = "https://www.patreon.com/techqueria/"
[[menu.main]]
    parent                           = "Donate"
    name                             = "Our Patreon Supporters"
    url                              = "/donate/patreon-supporters/"

[[menu.main]]
    name                             = "Resources"
    url                              = "/resources/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Career Growth"
    url                              = "/resources/career/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Conferences"
    url                              = "/resources/conferences/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Design"
    url                              = "/resources/design/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Entrepreneurship"
    url                              = "/resources/entrepreneurship/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Health Care"
    url                              = "/resources/health/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Housing"
    url                              = "/resources/housing/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Immigration"
    url                              = "/resources/immigration/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Legal Help"
    url                              = "/resources/legal/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Nonprofits"
    url                              = "/resources/nonprofits/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Open Source"
    url                              = "/resources/open-source/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Podcasts"
    url                              = "/resources/podcasts/"
[[menu.main]]
    parent                           = "Resources"
    name                             = "Similar Organizations"
    url                              = "/resources/similar-organizations/"

[[menu.main]]
    name                             = "Support Us"
    url                              = "/support-us/"
[[menu.main]]
    parent                           = "Support Us"
    name                             = "Become a volunteer"
    url                              = "/volunteer/"
[[menu.main]]
    parent                           = "Support Us"
    name                             = "Donate space"
    url                              = "/donate-space/"
[[menu.main]]
    parent                           = "Support Us"
    name                             = "Our Supporters"
    url                              = "/supporters/"

# Social Menu

[[menu.social]]
    name                             = "LinkedIn"
    url                              = "https://www.linkedin.com/company/techqueria/"
    identifier                       = "fab fa-lg fa-linkedin"

[[menu.social]]
    name                             = "Twitter"
    url                              = "https://twitter.com/Techqueria"
    identifier                       = "fab fa-lg fa-twitter"

# Slack Menu

[[menu.slack]]
    name                             = "Join our Slack"
    url                              = "https://goo.gl/forms/VRARl4qkkLj3BJLl1"
    identifier                       = "fab fa-lg fa-slack"

[[menu.slack]]
    name                             = "Login to Slack"
    url                              = "https://latinos.slack.com"
    identifier                       = "fas fa-lg fa-sign-in-alt"

# Sitemap
# Should always be 9 items

# About
# Blog
# Code of Conduct
# Communities
# Contact
# Donate
# Events
# Press
# Resources
# Shop
# Sponsor Us
# Team

[[menu.sitemap]]
  name = "About"
  url = "/about/"
[[menu.sitemap]]
  name = "Blog"
  url = "/blog/"
[[menu.sitemap]]
  name = "Code of Conduct"
  url = "/code-of-conduct/"
[[menu.sitemap]]
  name = "Communities"
  url = "/communities/"
[[menu.sitemap]]
  name = "Contact"
  url = "/contact/"
[[menu.sitemap]]
  name = "Donate"
  url = "/donate/"
[[menu.sitemap]]
  name = "Events"
  url = "/events/"
[[menu.sitemap]]
  name = "Press"
  url = "/press/"
[[menu.sitemap]]
  name = "Resources"
  url = "/resources/"
[[menu.sitemap]]
  name = "Shop"
  url = "/shop/"
[[menu.sitemap]]
  name = "Support Us"
  url = "/support-us/"
[[menu.sitemap]]
  name = "Team"
  url = "/team/"

#
# Supporting Multiple Languages
#
[languages]
[languages.en]
  weight                             = 1
  languageName                       = "English"

[languages.es]
  weight                             = 2
  languageName                       = "Español"
  [languages.es.params]
    description                      = "Somos una comunidad de profesionales de Latinx en la industria de la tecnología. 🌮️ Este espacio pretende ser inclusivo, por lo que invitamos a Latinx desde las regiones del Caribe, Haití y Brasil, así como a aquellos que se identifican como Afro-Latinx o LGBTQ. El término Latinx se usa en lugar de Latino porque es un término neutral e inclusivo."

[[languages.es.menu.main]]
    name                             = "Sobre nosotros"
    url                              = "/about/"
[[languages.es.menu.main]]
    parent                           = "Sobre nosotros"
    name                             = "Blog"
    url                              = "/blog/"
[[languages.es.menu.main]]
    parent                           = "Sobre nosotros"
    name                             = "Marca"
    url                              = "/about/brand/"
[[languages.es.menu.main]]
    parent                           = "Sobre nosotros"
    name                             = "Código de Conducta"
    url                              = "/code-of-conduct/"
[[languages.es.menu.main]]
    parent                           = "Sobre nosotros"
    name                             = "Gente"
    url                              = "/people/"
[[languages.es.menu.main]]
    parent                           = "Sobre nosotros"
    name                             = "Prensa"
    url                              = "/press/"
[[languages.es.menu.main]]
    parent                           = "Sobre nosotros"
    name                             = "Fotografías de Archivo"
    url                              = "/stock-photos/"
[[languages.es.menu.main]]
    parent                           = "Sobre nosotros"
    name                             = "Testimonios"
    url                              = "/testimonials/"

[[languages.es.menu.main]]
    name                             = "Comunidades"
    url                              = "/communities/"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Sede - Área de la Bahía"
    url                              = "/communities/bay-area/"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Sede - Los Ángeles"
    url                              = "/communities/los-angeles/"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Sede - Nueva York"
    url                              = "/communities/new-york-city/"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Grupo de Facebook"
    url                              = "https://www.facebook.com/groups/techqueria"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Página de Facebook"
    url                              = "https://www.facebook.com/techqueria"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Organización de GitHub"
    url                              = "https://github.com/techqueria"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Grupo de LinkedIn"
    url                              = "https://www.linkedin.com/groups/13500636"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Grupo de Meetup"
    url                              = "https://www.meetup.com/techqueria/"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Newsletter"
    url                              = "https://mailchi.mp/c12256627e10/techqueria-newsletter"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Slack Workspace"
    url                              = "/communities/slack/"
[[languages.es.menu.main]]
    parent                           = "Comunidades"
    name                             = "Canal de YouTube"
    url                              = "https://www.youtube.com/channel/UCUhXR0BOgyqrS1E_Sr4PVjQ"

[[languages.es.menu.main]]
    name                             = "Contacto"
    url                              = "/contact/"

[[languages.es.menu.main]]
    name                             = "Eventos"
    url                              = "/events/"

[[languages.es.menu.main]]
    name                             = "Patrocinadores"
    url                              = "/sponsors/"

[[languages.es.menu.main]]
    name                             = "Recursos"
    url                              = "/resources/"
[[languages.es.menu.main]]
    parent                           = "Recursos"
    name                             = "Desarrollo Profesional"
    url                              = "/resources/career/"
[[languages.es.menu.main]]
    parent                           = "Recursos"
    name                             = "Diseño"
    url                              = "/resources/design/"
[[languages.es.menu.main]]
    parent                           = "Recursos"
    name                             = "Emprendimiento"
    url                              = "/resources/entrepreneurship/"
[[languages.es.menu.main]]
    parent                           = "Recursos"
    name                             = "Cuidado de Salud"
    url                              = "/resources/health/"
[[languages.es.menu.main]]
    parent                           = "Recursos"
    name                             = "Inmigración"
    url                              = "/resources/immigration/"
[[languages.es.menu.main]]
    parent                           = "Recursos"
    name                             = "Ayuda Legal"
    url                              = "/resources/legal/"
[[languages.es.menu.main]]
    parent                           = "Recursos"
    name                             = "Open Source"
    url                              = "/resources/open-source/"
[[languages.es.menu.main]]
    parent                           = "Recursos"
    name                             = "Podcasts"
    url                              = "/resources/podcasts/"
