[build]
  publish = "dist"
  command = "gulp build"
[build.environment]
  TZ = "America/Los_Angeles"
  tz = "America/Los_Angeles"

[context.production.environment]
  HUGO_VERSION = "0.48"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.48"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://techqueria.netlify.com/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "https://blog.techqueria.org/*"
  to = "/blog:splat"
  status = 301
