baseURL                       = "https://techqueria.org/"
buildFuture                   = true
copyright                     = "This work is licensed under MIT."
enableEmoji                   = true
enableRobotsTXT               = true
footnoteReturnLinkContents    = "↩"
metaDataFormat                = "yaml"
title                         = "Techqueria"

# Language
languageCode                  = "en-us"
DefaultContentLanguage        = "en"

# Categories
preserveTaxonomyNames         = false

# Code
pygmentsCodefences            = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle                 = "manni"

# Internal Templates
# googleAnalytics             = ""
# disqusShortname             = ""

# RSS
[outputs]
    home                      = ["HTML", "RSS"]
    page                      = ["HTML"]

[outputFormats]
    [outputFormats.RSS]
        mediatype             = "application/rss"
        baseName              = "feed"

# SEO
[params]
    description               = "We're a community of Latinx professionals in the tech industry. 🌮️ This space aims to be inclusive so we invite Latinx from the regions of the Caribbean, Haiti, and Brazil as well as those who identify as Afro-Latinx or LGBTQ. The term Latinx is used instead of Latino because it is a gender-neutral and inclusive term."
    copyright                 = "Techqueria.org"
    year                      = 2015
    og_image                  = "https://i.imgur.com/O2YyA3E.png"
    logo                      = "https://i.imgur.com/iJpGY6L.png"
    locale                    = "en_US"

# Social Links
[social]
    email                     = "organizers@techqueria.org"
    facebook                  = "techqueria"
    instagram                 = "techqueriala"
    linkedin                  = "company/techqueria"
    meetup                    = "techqueria"
    twitter                   = "TechqueriaSF"
    youtube                   = "UCUhXR0BOgyqrS1E_Sr4PVjQ"

# Permalinks
[permalinks]
  blog                        = "/blog/:year/:month/:day/:title/"
  testimonials                = "/testimonials/:year/:month/:day/:title/"
  press                       = "/press/:year/:month/:day/:title/"

[author]
    name                      = "Techqueria"
    copyright                 = "©️ Techqueria.org"

[[menu.social]]
    name                      = "Facebook"
    url                       = "https://www.facebook.com/groups/techqueria"
    identifier                = "fab fa-lg fa-facebook"

[[menu.social]]
    name                      = "Twitter"
    url                       = "https://twitter.com/techqueriasf"
    identifier                = "fab fa-lg fa-twitter"

# Homepage
# 1. About
# 2. Blog
# 3. Code of Conduct
# 4. Communities
# 5. Contact
# 6. Events
# 7. People
# 8. Press
# 9. Resources
# 10. Sponsors
# 11. Stock Photos
# 12. Testimonials

# Menu
# 1. About
# 2. Communities
# 3. Contact
# 4. Events
# 5. Resources
# 6. Sponsors

[[menu.main]]
    name                      = "About"
    url                       = "/about/"
[[menu.main]]
    parent                    = "About"
    name                      = "Blog 📝"
    url                       = "/blog/"
[[menu.main]]
    parent                    = "About"
    name                      = "Brand 🎨"
    url                       = "/about/brand/"
[[menu.main]]
    parent                    = "About"
    name                      = "Code of Conduct 🌼"
    url                       = "/code-of-conduct/"
[[menu.main]]
    parent                    = "About"
    name                      = "People 👥"
    url                       = "/people/"
[[menu.main]]
    parent                    = "About"
    name                      = "Press 📰️"
    url                       = "/press/"
[[menu.main]]
    parent                    = "About"
    name                      = "Stock Photos 📸"
    url                       = "/photos/"
[[menu.main]]
    parent                    = "About"
    name                      = "Testimonials 💌"
    url                       = "/testimonials/"

[[menu.main]]
    name                      = "Communities"
    url                       = "/communities/"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Chapter - Bay Area"
    url                       = "/communities/bay-area/"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Chapter - Los Angeles"
    url                       = "/communities/los-angeles/"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Chapter - New York City"
    url                       = "/communities/new-york-city/"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Facebook Group"
    url                       = "https://www.facebook.com/groups/techqueria"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Facebook Page"
    url                       = "https://www.facebook.com/techqueria"
[[menu.main]]
    parent                    = "Communities"
    name                      = "GitHub Organization"
    url                       = "https://github.com/techqueria"
[[menu.main]]
    parent                    = "Communities"
    name                      = "LinkedIn Group"
    url                       = "https://www.linkedin.com/groups/13500636"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Meetup Group"
    url                       = "https://www.meetup.com/techqueria/"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Newsletter"
    url                       = "https://mailchi.mp/c12256627e10/techqueria-newsletter"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Slack Workspace"
    url                       = "/communities/slack/"
[[menu.main]]
    parent                    = "Communities"
    name                      = "YouTube Channel"
    url                       = "https://www.youtube.com/channel/UCUhXR0BOgyqrS1E_Sr4PVjQ"

[[menu.main]]
    name                      = "Contact"
    url                       = "/contact/"

[[menu.main]]
    name                      = "Events"
    url                       = "/events/"

[[menu.main]]
    name                      = "Sponsors"
    url                       = "/sponsors/"

[[menu.main]]
    name                      = "Resources"
    url                       = "/resources/"
[[menu.main]]
    parent                    = "Resources"
    name                      = "Career Growth 💼️"
    url                       = "/resources/career/"
[[menu.main]]
    parent                    = "Resources"
    name                      = "Design 🖌️"
    url                       = "/resources/design/"
[[menu.main]]
    parent                    = "Resources"
    name                      = "Health Care 🏥"
    url                       = "/resources/health/"
[[menu.main]]
    parent                    = "Resources"
    name                      = "Immigration 📄"
    url                       = "/resources/immigration/"
[[menu.main]]
    parent                    = "Resources"
    name                      = "Legal Help ⚖️"
    url                       = "/resources/legal/"
[[menu.main]]
    parent                    = "Resources"
    name                      = "Open Source 🔧️"
    url                       = "/resources/open-source/"
[[menu.main]]
    parent                    = "Resources"
    name                      = "Podcasts 🎙️"
    url                       = "/resources/podcasts/"
